# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassProject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'mass_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MassProjectReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('e_sent', models.IntegerField()),
                ('initial', models.IntegerField()),
                ('subscribed', models.IntegerField()),
                ('unsubscribed', models.IntegerField()),
                ('bounced', models.IntegerField()),
                ('mozart_rows', models.IntegerField()),
                ('e_sent_today', models.IntegerField()),
                ('e_sent_week', models.IntegerField()),
                ('e_sent_month', models.IntegerField()),
                ('freq_0', models.IntegerField()),
                ('freq_1m', models.IntegerField()),
                ('freq_3m', models.IntegerField()),
                ('freq_6m', models.IntegerField()),
                ('freq_recu_4m', models.IntegerField()),
                ('last_date', models.DateField()),
                ('project_id', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
            options={
                'db_table': 'mass_project_report',
                'managed': False,
            },
        ),
    ]
