# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20170815_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='massproject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='massprojectreport',
            table=None,
        ),
    ]
