# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_massprojectreport_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massprojectreport',
            name='last_date',
        ),
    ]
